name: Remote-SSH Bug
description: File a bug/issue for the Remote-SSH extension
title: "[Remote-SSH BUG]: "
labels: ["ssh"]
body:
	- type: checkboxes
	  attributes:
	    label: Is there an existing issue for this bug?
	    description: Please search to see if an issue already exists for the bug you encountered.
	    options:
	    - label: I have searched the existing issues
	      required: true