name: Remote-SSH Bug
description: File a bug/issue for the Remote-SSH extension
title: "[Remote-SSH BUG]: "
labels: ["ssh"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this bug?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true 
  - type: checkboxes
    attributes:
      label: Did you check the troubleshooting docs?
      description: [troubleshoot docs](https://code.visualstudio.com/docs/remote/troubleshooting)
      options:
      - label: I have checked the docs
        required: true
  - type: textarea
    attributes:
      label: VSCode Version
      description: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Local OS Version
      description: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Remote OS Version
      description: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Remote-SSH Logs
      description:  You can find them through going to the `terminal` on your remote VS Code 
      window then selecting the tab `output` then select `remote-ssh` from the dropdown
      value: |
          - OS:
          - Node:
          - npm:
      render: markdown
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Does this issue occur when you try this locally?
      description: To do this, run the same SSH connection command outside of VS Code in a separate shell like Terminal or PowerShell.
       If your SSH connection still does not work when you try the same command locally it probably has to do with your SSH connection and not with our remote-SSH extension. 
      options:
          - yes it work locally
          - no, it doesn't work locally
  - type: dropdown
    attributes:
      label: Does this issue occur when you try this locally AND all extensions are disabled?
      description: To do this, run the same SSH connection command outside of VS Code in a separate shell like Terminal or PowerShell.
       If your SSH connection still does not work when you try the same command this way it likely relates to a extension issue. 
      options:
          - yes it work locally
          - no, it doesn't work locally
  - type: checkboxes
    attributes:
      label: Did you check the troubleshooting docs?
      description: [troubleshoot docs](https://code.visualstudio.com/docs/remote/troubleshooting)
      options:
      - label: I have checked the docs
        required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
  
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false